<?php
require_once 'includes/init.php';
require_once 'includes/excel.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

function v($cell){
    return trim((string)$cell->getFormattedValue());
}

$headerDisplay=[];
$items=[];
$totalFee=0;
$uploaded=false;
$error='';

if(!empty($_FILES['excel']['tmp_name'])){

try{

$spreadsheet = IOFactory::load($_FILES['excel']['tmp_name']);
$sheet=$spreadsheet->getActiveSheet();

$highestRow=$sheet->getHighestRow();

$company='';
$dateFrom=null;
$dateTo=null;
$generated=null;

/* ===== READ HEADER ===== */

for($i=1;$i<=10;$i++){

$k=v($sheet->getCell("A$i"));
$val=v($sheet->getCell("B$i"));

if($k=='Company Name') $company=$val;

if($k=='Date Range'){
    if(preg_match('/(\d{4}-\d{2}-\d{2}).*(\d{4}-\d{2}-\d{2})/',$val,$m)){
        $dateFrom=$m[1];
        $dateTo=$m[2];
    }
}

if(strpos($val,'Generated by Lalamove')!==false){
    if(preg_match('/(\d{4}-\d{2}-\d{2}.*)$/',$val,$m)){
        $generated=$m[1];
    }
}

if($k!=''){
$headerDisplay[]=[
'label'=>$k,
'value'=>$val
];
}

}

/* ===== DUPLICATE CHECK ===== */

$isDuplicate=0;

$chk=$pdo->prepare("
SELECT COUNT(*)
FROM lalamove_reports
WHERE company_name=? AND date_from=? AND date_to=?
");

$chk->execute([$company,$dateFrom,$dateTo]);

if($chk->fetchColumn()>0)$isDuplicate=1;

/* ===== INSERT REPORT ===== */

$stmt=$pdo->prepare("
INSERT INTO lalamove_reports
(company_name,date_from,date_to,total_orders,total_fee,generated_time,is_duplicate)
VALUES (?,?,?,?,0,?,?)
");

$stmt->execute([
$company,
$dateFrom,
$dateTo,
0,
$generated,
$isDuplicate
]);

$reportId=$pdo->lastInsertId();

/* ===== FIND TABLE HEADER ===== */

$headerRow=0;

for($r=1;$r<=20;$r++){

if(strtoupper(v($sheet->getCell("C$r")))=="ORDER ID"){
$headerRow=$r;
break;
}

}

if(!$headerRow){
throw new Exception("Không tìm thấy bảng dữ liệu ORDER ID");
}

/* ===== READ ITEMS ===== */

for($row=$headerRow+1;$row<=$highestRow;$row++){

$order=v($sheet->getCell("C$row"));
$time=v($sheet->getCell("D$row"));
$feeRaw=v($sheet->getCell("G$row"));

if($order=='')continue;

$fee=abs((float)$feeRaw);

$totalFee+=$fee;

$items[]=[
'created_time'=>$time,
'order_path'=>$order,
'pickup'=>'',
'dropoff'=>'',
'distance'=>0,
'special'=>'',
'fee'=>$fee
];

}

/* ===== INSERT ITEMS ===== */

$stmtItem=$pdo->prepare("
INSERT INTO lalamove_report_items
(report_id,created_time,order_path,pickup_address,dropoff_address,distance_km,special_request,fee)
VALUES (?,?,?,?,?,?,?,?)
");

foreach($items as $it){

$stmtItem->execute([
$reportId,
$it['created_time'],
$it['order_path'],
$it['pickup'],
$it['dropoff'],
$it['distance'],
$it['special'],
$it['fee']
]);

}

$pdo->prepare("UPDATE lalamove_reports SET total_fee=?,total_orders=? WHERE id=?")
->execute([$totalFee,count($items),$reportId]);

$uploaded=true;

}catch(Exception $e){
$error=$e->getMessage();
}

}

include 'includes/header.php';
?>

<div class="container">

<h3 class="mb-3">Upload báo cáo Lalamove</h3>

<form method="post" enctype="multipart/form-data" class="mb-4">
<input type="file" name="excel" required class="form-control" onchange="this.form.submit()">
</form>

<?php if($error): ?>
<div class="alert alert-danger"><?=$error?></div>
<?php endif; ?>

<?php if($uploaded): ?>

<?php if($isDuplicate): ?>
<div class="alert alert-warning">⚠ Báo cáo này đã tồn tại</div>
<?php endif; ?>

<div class="card mb-3">
<div class="card-header fw-bold">Thông tin chung</div>

<table class="table table-sm">

<?php foreach($headerDisplay as $h): ?>

<tr>
<td width="30%" class="text-muted"><?=$h['label']?></td>
<td><?=htmlspecialchars($h['value'])?></td>
</tr>

<?php endforeach; ?>

</table>

</div>

<table class="table table-bordered table-striped">

<thead class="table-light">
<tr>
<th>Thời gian</th>
<th>Mã đơn</th>
<th class="text-end">Phí</th>
</tr>
</thead>

<tbody>

<?php foreach($items as $it): ?>

<tr>
<td><?=$it['created_time']?></td>
<td><?=$it['order_path']?></td>
<td class="text-end"><?=number_format($it['fee'],0,',','.')?> ₫</td>
</tr>

<?php endforeach; ?>

</tbody>

<tfoot>

<tr class="fw-bold">
<td colspan="2">Tổng</td>
<td class="text-end"><?=number_format($totalFee,0,',','.')?> ₫</td>
</tr>

</tfoot>

</table>

<a href="lalamove_reports.php" class="btn btn-secondary">Quản lý báo cáo</a>

<?php endif; ?>

</div>

<?php include 'includes/footer.php'; ?>

